import "@/styles/globals.css";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Host de Counter Strike 2 no Brasil | CS2 Profissional",
    description: "Hospede seu servidor de Counter Strike 2 no Brasil com alto desempenho, proteção Anti DDoS, baixa latência e painel intuitivo. Ideal para partidas competitivas e personalizadas.",
    keywords: [
        "RazeHost.com.br",
        "RazeHost",
        "Raze Host",
        "RazeHost Brasil",
        "RazeHost Games",
        "RazeHost VPS",
        "host de FiveM",
        "hospedagem de FiveM",
        "FiveM Brasil",
        "FiveM servidor dedicado",
        "servidor de FiveM com proteção DDoS",
        "host de CS2",
        "A melhor host de Counter Strike 2",
        "hospedagem de CS2",
        "Counter Strike 2 Brasil",
        "VPS CS2",
        "host de Conan Exiles",
        "host DayZ",
        "VPS DayZ",
        "VPS Rust",
        "Hospedagem de Rust",
        "Host Rust",
        "VPS para jogos",
        "host de Project Zomboid",
        "Project Zomboid server",
        "host 7 Days to Die",
        "servidor de Satisfactory",
        "servidor de Terraria",
        "servidor de MU Online",
        "host de Tibia",
        "VPS Tibia",
        "hospedagem de Tibia",
        "servidor dedicado para Tibia",
        "servidor de MU Online",
        "host de V Rising",
        "servidor de V Rising",
        "V Rising Brasil",
        "host de ARK",
        "hospedagem de ARK",
        "ARK Survival Ascended server",
        "servidor de ARK Survival Ascended",
        "host de Unturned",
        "Unturned server",
        "hospedagem de Unturned",
        "VPS gamer",
        "VPS gamer Brasil",
        "VPS gamer com anti DDoS",
        "VPS Brasil",
        "VPS no Brasil",
        "VPS Ryzen",
        "VPS Gamer Ryzen",
        "VPS para FiveM",
        "VPS Windows",
        "VPS Linux",
        "VPS barato",
        "VPS performance",
        "VPS com alta performance",
        "VPS para jogos online",
        "servidores dedicados",
        "servidor dedicado barato",
        "VPS para trading",
        "VPS Trader",
        "VPS Trader Brasil",
        "VPS Cloud",
        "VPS NVMe",
        "servidor dedicado NVMe",
        "servidor dedicado Ryzen",
        "servidor dedicado gamer",
        "anti DDoS",
        "servidor com proteção DDoS",
        "VPS com proteção DDoS",
        "Cloudflare",
        "servidor seguro",
        "servidor rápido no Brasil",
        "data center no Brasil",
        "host de jogos",
        "hospedagem de jogos online",
        "servidor de jogos multiplayer",
        "servidor de CS2",
        "servidor de Satisfactory",
        "servidor de ARK Survival Ascended",
        "servidor de Valheim",
        "servidor de GTA RP",
        "servidor de Ragnarok Online",
        "host de ARK",
        "servidor de Counter Strike",
        "servidor de CS:GO",
        "servidor de RedM",
        "servidor de V Rising",
        "servidor de Unturned",
        "cloud server",
        "cloud hosting",
        "host de mta",
        "host rust brasil",
        "fivem brasil",
        "servidor de cs2",
        "cs2 brasil",
        "cs2 host",
        "cloud gaming",
        "hospedagem web gamer",
        "hospedagem para site de jogos",
        "registro de domínio gamer",
        "domínio para site de jogos"
    ],
    openGraph: {
        title: 'Host de Counter Strike 2 | RazeHost',
        description: 'A melhor hospedagem de CS2 no Brasil com painel de gerenciamento simples, proteção Anti DDoS e desempenho profissional para suas partidas.',
        url: 'https://www.razehost.com.br/',
        siteName: 'RazeHost',
        images: ['/banner.webp']
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Host de Counter Strike 2 | RazeHost',
        description: 'A melhor hospedagem de CS2 no Brasil com painel de gerenciamento simples, proteção Anti DDoS e desempenho profissional para suas partidas.',
        images: ['/banner.webp'],
    },
    icons: {
        icon: "/favicon.ico",
    },
};

export default function Layout({ children }: { children: React.ReactNode; }) {
    return (
        <>
            <script
                type="application/ld+json"
                dangerouslySetInnerHTML={{
                    __html: JSON.stringify({
                        "@context": "https://schema.org",
                        "@type": "WebPage",
                        name: "Host de Counter Strike 2 no Brasil | CS2 Profissional",
                        description:
                            "Hospede seu servidor de Counter Strike 2 no Brasil com alto desempenho, proteção Anti DDoS, baixa latência e painel intuitivo. Ideal para partidas competitivas e personalizadas.",
                        url: "https://www.razehost.com.br/",
                        author: {
                            "@type": "Organization",
                            name: "RazeHost",
                        },
                        potentialAction: {
                            "@type": "SearchAction",
                            target: "https://www.razehost.com.br/?s={search_term_string}",
                            "query-input": "required name=search_term_string",
                        },
                    }),
                }}
            />

            {children}
        </>
    );
}
