import "@/styles/globals.css";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Host de Rust no Brasil | Hospedagem de Alta Performance",
    description: "A melhor hospedagem de servidores Rust no Brasil, com alto desempenho, painel de gerenciamento fácil e proteção anti-DDoS. Instale mods, jogue com seus amigos e aproveite uma infraestrutura otimizada para o melhor desempenho de Rust.",
    keywords: [
        "RazeHost.com.br",
        "RazeHost",
        "Raze Host",
        "RazeHost Brasil",
        "RazeHost Games",
        "RazeHost VPS",
        "host de FiveM",
        "hospedagem de FiveM",
        "FiveM Brasil",
        "FiveM servidor dedicado",
        "servidor de FiveM com proteção DDoS",
        "host de Minecraft",
        "A melhor host de Minecraft",
        "hospedagem de Minecraft",
        "Minecraft Brasil",
        "VPS Minecraft",
        "host de Conan Exiles",
        "host DayZ",
        "VPS DayZ",
        "VPS Rust",
        "Hospedagem de Rust",
        "Host Rust",
        "VPS para jogos",
        "host de Project Zomboid",
        "Project Zomboid server",
        "host 7 Days to Die",
        "servidor de Satisfactory",
        "host de Terraria",
        "servidor de MU Online",
        "host de Tibia",
        "VPS Tibia",
        "hospedagem de Tibia",
        "servidor dedicado para Tibia",
        "servidor de MU Online",
        "host de V Rising",
        "servidor de V Rising",
        "V Rising Brasil",
        "host de ARK",
        "hospedagem de ARK",
        "ARK Survival Evolved server",
        "servidor de ARK Survival Evolved",
        "host de Unturned",
        "Unturned server",
        "hospedagem de Unturned",
        "VPS gamer",
        "VPS gamer Brasil",
        "VPS gamer com anti DDoS",
        "VPS Brasil",
        "VPS no Brasil",
        "VPS Ryzen",
        "VPS Gamer Ryzen",
        "VPS para FiveM",
        "VPS Windows",
        "VPS Linux",
        "VPS barato",
        "VPS performance",
        "VPS com alta performance",
        "VPS para jogos online",
        "servidores dedicados",
        "servidor dedicado barato",
        "VPS para trading",
        "VPS Trader",
        "VPS Trader Brasil",
        "VPS Cloud",
        "VPS NVMe",
        "servidor dedicado NVMe",
        "servidor dedicado Ryzen",
        "servidor dedicado gamer",
        "anti DDoS",
        "servidor com proteção DDoS",
        "VPS com proteção DDoS",
        "Cloudflare",
        "servidor seguro",
        "servidor rápido no Brasil",
        "data center no Brasil",
        "host de jogos",
        "hospedagem de jogos online",
        "servidor de jogos multiplayer",
        "servidor de Terraria",
        "servidor de Satisfactory",
        "servidor de Ark Survival Evolved",
        "servidor de Valheim",
        "servidor de GTA RP",
        "servidor de Ragnarok Online",
        "host de ARK",
        "servidor de Counter Strike",
        "servidor de CS:GO",
        "servidor de RedM",
        "servidor de V Rising",
        "servidor de Unturned",
        "cloud server",
        "cloud hosting",
        "host de mta",
        "host rust brasil",
        "fivem brasil",
        "servidor de minecraft",
        "minecraft bedrock",
        "bedrock host",
        "cloud gaming",
        "hospedagem web gamer",
        "hospedagem para site de jogos",
        "registro de domínio gamer",
        "domínio para site de jogos",
        "Rust server",
        "servidor de Rust",
        "servidor dedicado Rust",
        "servidor Rust Brasil",
        "servidor de Rust com DDoS protection",
        "Rust game hosting",
        "hospedagem Rust",
        "VPS Rust com anti DDoS",
        "servidor Rust com alta performance",
        "host de Rust com SSD NVMe"
      ]      
    openGraph: {
        title: 'Host de Rust no Brasil | RazeHost',
        description: 'Hospedagem de servidores Rust no Brasil com alto desempenho, painel de fácil gerenciamento e proteção anti-DDoS. Jogue com seus amigos e aproveite a infraestrutura otimizada para Rust.',
        url: 'https://razehost.com.br/game/rust',
        siteName: 'RazeHost',
        images: ['/banner.webp'],
        type: 'website',
        locale: 'pt_BR',
    },
    twitter: {
        card: 'summary_large_image',
        title: 'Host de Rust no Brasil | RazeHost',
        description: 'A melhor hospedagem de Rust no Brasil com painel de gerenciamento intuitivo, alta performance e proteção anti-DDoS. Instale mods, jogue com amigos e aproveite a infraestrutura otimizada para Rust.',
        images: ['/banner.webp'],
        creator: '@RazeHostBR',
    },
    icons: {
        icon: "/favicon.ico",
    },
};


export default function Layout({ children }: { children: React.ReactNode; }) {
    return (
        <>
            {children}
        </>
    );
}